# ~/.bashrc (Mac OS)
# This is basically a copy of .bashrc but with some Mac specific changes

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
HISTSIZE=100000

# Append to the history file, don't overwrite it
shopt -s histappend

# Aliases
alias df='df -h'
alias diff='colordiff -y --width=$COLUMNS'
alias ls='gls --color=auto --group-directories-first'
alias ll='ls -lh'
alias la='ll -a'
alias grep='grep --color=auto'
alias mkdir='gmkdir -pv'
alias rsync='/usr/local/bin/rsync -a -v -h -L --info=progress2'


# Bash completion
if [ -f $(brew --prefix)/etc/bash_completion ]; then
    . $(brew --prefix)/etc/bash_completion
fi

# Base16 Shell
BASE16_SHELL="$HOME/.dotfiles/theme/base16-shell/"
[ -n "$PS1" ] && \
    [ -s "$BASE16_SHELL/profile_helper.sh" ] && \
        eval "$("$BASE16_SHELL/profile_helper.sh")"

# Prompt
PS1='\[\e[0;32m\]\W\[\e[0m\] \[\e[0;34m\]\$\[\e[0m\] '
