call plug#begin('~/.vim/plugged')

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'preservim/nerdtree'
Plug 'leafgarland/typescript-vim'
Plug 'peitalin/vim-jsx-typescript'
Plug 'chrisbra/vim-autosave'

call plug#end()

syntax enable

set background=dark 
set backspace=indent,eol,start      " improved backspace
set encoding=utf-8                  " always use UTF-8
set expandtab                       " expand tabs to spaces
set fillchars=vert:│                " vertical fill char
set incsearch                       " incremental search
set ignorecase                      " case insensitive search
set paste                           " use paste mode instead of auto-format
set scrolloff=4                     " scroll offset
set showcmd                         " show last command
set shiftwidth=4                    " shift width (indent)
set softtabstop=4                   " treat four spaces like a tab (backspace)
set tabstop=4                       " tab stop
set undofile                        " persistent undo
set undodir=$HOME/.vim/undo
set wildmenu                        " visual autocomplete for command menu

filetype indent on                  " file type specific indents 

" exit insertion mode
imap jk <Esc>

" turn off search hightlight
nnoremap <leader><space> :nohlsearch<CR>    

" Airline
let g:airline_theme='deus'
let g:airline_powerline_fonts = 1

set noshowmode  " to get rid of thing like --INSERT--

map <C-j> <C-W>j
map <C-k> <C-W>k
map <C-h> <C-W>h
map <C-l> <C-W>l

" No background for vertical fill char
highlight VertSplit cterm=NONE


