syntax enable

let base16colorspace=256
colors base16-tomorrow

set background=dark
set incsearch
set number
set scrolloff=3
set showcmd
set showmatch
set softtabstop=4
set tabstop=4
set wildmenu

filetype indent on

" Visually select the text that was last edited/pasted
nnoremap gV `[v`]
