eval "$(/opt/homebrew/bin/brew shellenv)"
export HOMEBREW_NO_ENV_HINTS=1

export EDITOR=hx

export GOPATH=$HOME/.go
export GOROOT="/opt/homebrew/opt/go/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

# Own programs
export PATH=$HOME/.local/bin:$PATH

#AWSume alias to source the AWSume script
alias awsume="source awsume"

#Auto-Complete function for AWSume
fpath=(~/.awsume/zsh-autocomplete/ $fpath)
