export EDITOR=nvim

export GOPATH=$HOME/.go
export GOROOT="/opt/homebrew/opt/go/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

export PATH="/opt/homebrew/opt/node@18/bin:$PATH"

# Own programs
export PATH=$HOME/.local/bin:$PATH
