FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

source /opt/homebrew/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle yarn
antigen bundle zsh-users/zsh-autosuggestions

antigen theme https://github.com/grubersjoe/dotfiles.git zsh/theme

antigen apply

HISTFILE=~/.zsh_history
HISTSIZE=4096
SAVEHIST=4096

setopt autocd correct incappendhistory nomatch notify

bindkey -e
bindkey '^R' history-incremental-search-backward

# Completion system
zstyle :compinstall filename '/home/joe/.zshrc'
zstyle ':completion:*' list-dirs-first true

autoload -Uz compinit
compinit

if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

# Own programs
export PATH=$HOME/.local/bin:$PATH

# Homebrew
export PATH=$HOME/.docker/bin:$PATH
export PATH="/opt/homebrew/opt/mysql-client/bin:$PATH"
export PATH="/opt/homebrew/opt/php@8.2/bin:$PATH"
export PATH="$(brew --prefix)/opt/python@3/libexec/bin:$PATH"

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"

# Go
export GOPATH=$HOME/.go
export GOROOT="$(brew --prefix golang)/libexec"
export PATH="$PATH:${GOPATH}/bin:${GOROOT}/bin"

source <(kubectl completion zsh)
