FPATH="$(brew --prefix)/share/zsh/site-functions:${FPATH}"

source /opt/homebrew/share/antigen/antigen.zsh

antigen use oh-my-zsh

antigen bundle git
antigen bundle zsh-users/zsh-autosuggestions

antigen theme https://github.com/grubersjoe/dotfiles.git zsh/theme

antigen apply

HISTFILE=~/.zsh_history
HISTSIZE=4096
SAVEHIST=4096

setopt autocd correct incappendhistory nomatch notify

bindkey -e
bindkey '^R' history-incremental-search-backward

# Completion system
zstyle :compinstall filename '/home/joe/.zshrc'
zstyle ':completion:*' list-dirs-first true

autoload -Uz compinit
compinit

if [ -f ~/.aliases ]; then
  . ~/.aliases
fi

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "/opt/homebrew/opt/nvm/nvm.sh" ] && \. "/opt/homebrew/opt/nvm/nvm.sh"
[ -s "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm" ] && \. "/opt/homebrew/opt/nvm/etc/bash_completion.d/nvm"
