# ~/.bashrc (GNU/Linux)

# If not running interactively, don't do anything
case $- in
    *i*) ;;
        *) return;;
esac

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
HISTSIZE=10000

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Prompt
PS1='\[\e[1;37m\]\W\[\e[0m\] \[\e[1;34m\]⚡\[\e[0m\] '

# Set shell window title (gnome-terminal)
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'

# Make less more friendly for non-text input files, see lesspipe(1)
[ -x /usr/bin/lesspipe ] && eval "$(SHELL=/bin/sh lesspipe)"

# Enable bash completion in interactive shells
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

# Environmental variables and exports
export EDITOR="vim"
export CL_JDK="/usr/lib/jvm/default"
export WEBIDE_JDK="/usr/lib/jvm/default"
export QT_STYLE_OVERRIDE=GTK+

# Aliases
alias aur='yaourt'
alias cl='clear'
alias df='df -h'
alias diff='colordiff -y --width=$COLUMNS'
alias ll='ls -lh'
alias ls='ls --color=auto --group-directories-first'
alias grep='grep --color=auto'
alias gsc='gnome-screenshot -i'
alias man='man -Len'
alias mkdir='mkdir -pv'
alias nano='vim'
alias open='xdg-open'

# Enable 256 color terminal
if [ -n "$DISPLAY" -a "$TERM" == "xterm" ]; then
    export TERM=xterm-256color
fi

# Adding ~/.bin and subdirectories to PATH
PATH+=":~/.bin"
for d in $HOME/.bin/*/; do
    PATH+=":$d"
done

# Ruby Gems
PATH="`ruby -e 'puts Gem.user_dir'`/bin:$PATH"

# Happy shell startup
fortune | lolcat
