# ~/.bash_profile (GNU/Linux)

# Ruby Gems
PATH=$PATH:$(ruby -rubygems -e "puts Gem.user_dir")/bin

# NPM packages
NPM_PACKAGES="${HOME}/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"

export EDITOR="vim"
export TERMINAL="gnome-terminal"

export ANDROID_HOME=~/.android-sdk/
export CL_JDK="/usr/lib/jvm/default"
export QT_STYLE_OVERRIDE=GTK+

[[ -f ~/.bashrc ]] && . ~/.bashrc

[[ -z $DISPLAY && $XDG_VTNR -eq 1 ]] && exec startx
