# ~/.bashrc (GNU/Linux)

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
HISTSIZE=10000

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Aliases
alias aur='yaourt'
alias df='df -h'
alias diff='colordiff -y --width=$COLUMNS'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -lh'
alias la='ll -a'
alias grep='grep --color=auto'
alias gsc='gnome-screenshot -i'
alias gparted='gksudo -k gparted'
alias mkdir='mkdir -pv'
alias open='xdg-open'

# Base16 Shell
BASE16_SHELL="$HOME/.dotfiles/theme/base16-shell/base16-tomorrow.dark.sh"
[[ -s $BASE16_SHELL ]] && source $BASE16_SHELL

# Prompt
PS1='\[\e[0;34m\]\W\[\e[0m\] \[\e[0;34m\]\$\[\e[0m\] '

# Set shell window title
PROMPT_COMMAND='echo -ne "\033]0;${PWD}\007"'

# Happy shell startup
echo -n $(tput setaf 3)
fortune chucknorris 
