# ~/.bashrc (GNU/Linux)

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

# Don't put duplicate lines or lines starting with space in the history.
# See bash(1) for more options
HISTCONTROL=ignoreboth
HISTSIZE=10000

# Append to the history file, don't overwrite it
shopt -s histappend

# Check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.
shopt -s checkwinsize

# Aliases
alias aur='yay'
alias dd='dd status=progress'
alias df='df -h'
alias diff='colordiff -y --width=$COLUMNS'
alias ls='ls --color=auto --group-directories-first'
alias ll='ls -lh'
alias la='ll -a'
alias lsblk='lsblk -o +LABEL'
alias grep='grep --color=auto'
alias mkdir='mkdir -pv'
alias rsync='rsync -avhL --ignore-existing --exclude-from=$HOME/.dotfiles/exclude-list.txt --info=progress2'
alias open='xdg-open'
alias ..='cd ..'
alias ...='cd ../../'

# Prompt
PS1='\[\e[0;32m\]\W\[\e[0m\] \[\e[0;34m\]\$\[\e[0m\] '

