# ~/.bash_profile (GNU/Linux)

export EDITOR="vim"
export TERMINAL="lxterminal"

# Local programs
PATH=${HOME}/.local/bin:$PATH

# Correct theming of Qt5 applications
export XDG_CURRENT_DESKTOP=GNOME
export QT_QPA_PLATFORMTHEME="qt5ct"

# Java
export CL_JDK="/usr/lib/jvm/default"
export ANDROID_HOME=~/.android-sdk/

# Ruby Gems
PATH="$(ruby -e 'print Gem.user_dir')/bin:$PATH"

# NPM packages
NPM_PACKAGES="${HOME}/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"

[[ -f ~/.bashrc ]] && . ~/.bashrc

# Start X 
if [ -z "$DISPLAY" ] && [ -n "$XDG_VTNR" ] && [ "$XDG_VTNR" -eq 1 ]; then
  exec startx
fi
